apiVersion: v1
kind: Pod
metadata:
 name: alpine-pod
 labels:
  app: alpine-pod
spec:
 containers:
 - name: alpine-container
   image: alpine:edge
   imagePullPolicy: IfNotPresent
   command: ["/bin/sh","-c","--"]
   args: ["while true; do sleep 60; done;"]
 restartPolicy: OnFailure
