apiVersion: v1
kind: Pod
metadata:
 name: nginx-pod
 labels:
  app: nginx
  env: non-prod
spec:
 containers:
 - name: nginx-pod
   image: nginx:alpine
   ports:
   - containerPort: 80
     protocol: TCP
   imagePullPolicy: IfNotPresent
 restartPolicy: OnFailure
